name: Bug Report (Android)
description: Report a bug or issue with CUStats for Android
title: "[Bug][Android]: "
labels: ["bug", "Android"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Tell us what went wrong.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it
      placeholder: "When I do X, the app does Y instead of Z..."
    validations:
      required: true

  - type: dropdown
    id: android-version
    attributes:
      label: Android Version
      options:
        - Android 16 (Baklava)
        - Android 15 (Vanilla Ice Cream)
        - Android 14 (Upside Down Cake)
        - Android 13 (Tiramisu)
        - Android 12 (Snow Cone)
        - Android 11
        - Android 10
        - Older version
        - Not sure
    validations:
      required: false

  - type: input
    id: device-model
    attributes:
      label: Device Model
      placeholder: "Samsung Galaxy S24"
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: "Find this in CUStats > About tab"
      placeholder: "1.5.0"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue
    validations:
      required: false
