name: Bug Report (iOS)
description: Report a bug or issue with CUStats for iOS
title: "[Bug][iOS]: "
labels: ["bug", "iOS"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Tell us what went wrong.

  - type: dropdown
    id: account-type
    attributes:
      label: Account Type
      description: Which account are you experiencing issues with?
      options:
        - Claude (claude.ai)
        - OpenAI Codex
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it
      placeholder: "When I do X, the app does Y instead of Z..."
    validations:
      required: true

  - type: dropdown
    id: ios-version
    attributes:
      label: iOS Version
      options:
        - iOS 26
        - iOS 18
        - iOS 17
        - iOS 16
        - iOS 15
        - Older version
        - Not sure
    validations:
      required: false

  - type: input
    id: device-model
    attributes:
      label: Device Model
      placeholder: "iPhone 15 Pro"
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: "Find this in CUStats > About tab"
      placeholder: "1.5.0"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue
    validations:
      required: false
