name: Bug Report (macOS)
description: Report a bug or issue with CUStats for macOS
title: "[Bug][macOS]: "
labels: ["bug", "macOS"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Tell us what went wrong.

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug and how to reproduce it
      placeholder: "When I do X, the app does Y instead of Z..."
    validations:
      required: true

  - type: dropdown
    id: macos-version
    attributes:
      label: macOS Version
      options:
        - macOS 26 (Tahoe)
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - macOS 12 (Monterey)
        - Older version
        - Not sure
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: App Version
      description: "Find this in CUStats > About tab"
      placeholder: "1.5.0"
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue
    validations:
      required: false
