name: Feature Request
description: Suggest a new feature or improvement for CUStats
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this feature solve? What are you trying to accomplish?
      placeholder: "I want to be able to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: "The app could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've tried..."
    validations:
      required: false

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the app does this relate to?
      options:
        - Usage Tracking (Live tab)
        - Historical Views (Overview tab)
        - Settings
        - Menu Bar Display
        - Multi-Account
        - Other
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any mockups, screenshots, or additional details
    validations:
      required: false
