name: Feedback
description: Share general feedback about CUStats
title: "[Feedback]: "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        We'd love to hear your thoughts! Share your experience with CUStats.

  - type: dropdown
    id: account-type
    attributes:
      label: Account Type
      description: Which account are you providing feedback about?
      options:
        - Claude (claude.ai)
        - OpenAI Codex
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - macOS
        - iOS
        - Android
    validations:
      required: true

  - type: dropdown
    id: os-version
    attributes:
      label: OS Version
      description: What version of your operating system are you using?
      options:
        - macOS 26 (Tahoe)
        - macOS 15 (Sequoia)
        - macOS 14 (Sonoma)
        - macOS 13 (Ventura)
        - macOS 12 (Monterey)
        - iOS 26
        - iOS 18
        - iOS 17
        - iOS 16
        - iOS 15
        - Android 16 (Baklava)
        - Android 15 (Vanilla Ice Cream)
        - Android 14 (Upside Down Cake)
        - Android 13 (Tiramisu)
        - Android 12 (Snow Cone)
        - Android 11
        - Android 10
        - Older version
        - Not sure
    validations:
      required: false

  - type: dropdown
    id: type
    attributes:
      label: Feedback Type
      description: What kind of feedback is this?
      options:
        - General Experience
        - User Interface / Design
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: sentiment
    attributes:
      label: Overall Sentiment
      description: How do you feel about CUStats?
      options:
        - Positive
        - Neutral
        - Needs Improvement
    validations:
      required: true

  - type: textarea
    id: feedback
    attributes:
      label: Your Feedback
      description: Tell us what's on your mind
      placeholder: "I think..."
    validations:
      required: true

  - type: textarea
    id: suggestions
    attributes:
      label: Suggestions
      description: Any specific suggestions for improvement?
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: App Version (optional)
      description: "Find this in CUStats > About tab"
      placeholder: "1.5.0"
    validations:
      required: false
